# Generated by Django 4.1.7 on 2023-04-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'MY PRODUCTS', 'verbose_name_plural': 'THE PRODUCTS'},
        ),
    ]
